export const lamps = [
    {
        id: 22,
        style: "Luxury",
        countOfBulbs: 1,
        brand: "Angelpoise",
        priceInUAH: 5345.0,
        room: "BEDROOM",
        heightInMm: 345,
        widthInMm: 123,
        type: "BEDSIDE",
        lightBulbs: [],
        shops: [],
    },
    {
        id: 26,
        style: "Design",
        countOfBulbs: 3,
        brand: "LouisPoulsen",
        priceInUAH: 1050.0,
        room: "OFFICE",
        heightInMm: 330,
        widthInMm: 100,
        type: "TASK",
        lightBulbs: [],
        shops: [],
    },
    {
        id: 28,
        style: "Modern",
        countOfBulbs: 1,
        brand: "Nordlux",
        priceInUAH: 1000.0,
        room: "OFFICE",
        heightInMm: 330,
        widthInMm: 100,
        type: "TASK",
        lightBulbs: [],
        shops: [],
    },
    {
        id: 31,
        style: "Classic",
        countOfBulbs: 3,
        brand: "Nordlux",
        priceInUAH: 2000.0,
        room: "BEDROOM",
        heightInMm: 230,
        widthInMm: 120,
        type: "BEDSIDE",
        lightBulbs: [],
        shops: [],
    },
    {
        id: 32,
        style: "Modern",
        countOfBulbs: 2,
        brand: "Artemide",
        priceInUAH: 2341.0,
        room: "BEDROOM",
        heightInMm: 234,
        widthInMm: 156,
        type: "BEDSIDE",
        lightBulbs: [],
        shops: [],
    },
    {
        id: 34,
        style: "Classic",
        countOfBulbs: 1,
        brand: "AstroLighting",
        priceInUAH: 6789.0,
        room: "BEDROOM",
        heightInMm: 234,
        widthInMm: 56,
        type: "BEDSIDE",
        lightBulbs: [],
        shops: [],
    },
    {
        id: 35,
        style: "Luxury",
        countOfBulbs: 1,
        brand: "Artemide",
        priceInUAH: 3452.0,
        room: "BEDROOM",
        heightInMm: 345,
        widthInMm: 237,
        type: "BEDSIDE",
        lightBulbs: [],
        shops: [],
    },
    {
        id: 36,
        style: "Classic",
        countOfBulbs: 1,
        brand: "Nordlux",
        priceInUAH: 23.0,
        room: "BEDROOM",
        heightInMm: 34,
        widthInMm: 26,
        type: "BEDSIDE",
        lightBulbs: [],
        shops: [],
    },
];
